version: "3.3"
services:
  my-helper-api-db:
    container_name: my-helper-api-mysql-db
    image: mysql:5.7
    restart: always
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: "my_helper_api_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - vol-my-helper-api-db:/var/lib/mysql
volumes:
  vol-my-helper-api-db:
